version: '3'
services:
  postgres:
    image: postgres:16.0-alpine
    container_name: my_payload_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: payload_db
    ports:
      - "5432:5432"  # Expose port 5432 on your local machine
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
